services:
  ytschool.api.cms:
    image: ${DOCKER_REGISTRY-}ytschoolapicms
    container_name: ytschool-cms-api
    build:
      context: .
      dockerfile: YTSchool.Api.Cms/Dockerfile
    ports:
      - 7000:8080
      - 7001:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ytschool.cms.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  
  ytschool.cms.postgres:
    image: postgres:17.2 # or latest
    container_name: ytschool-cms-postgres
    environment:
      POSTGRES_DB: ytschool_cms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ytschool.cms.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: ytschool-cms-aspire
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
